### ISSUE TITLE
Output from renderProp

### ISSUE THREAD

**Issue by bailer** [theKashey/react-remock#7]
Hello,

I'm wondering why there is a difference of the output from `defaultMock` and `renderProp` in `src/mocks.tsx`. In `defaultMock` you get the `props` and `itWas` only contains the name of the original component. But in the case of `renderProp` the `props` are omitted and the whole component is put into `itWas`. I'm guessing there is some reason behind this (which I can't figure out) but this means that `itWas` will change when e.g. you change the propTypes or defaultProps of the component you are mocking. This becomes an issue when using snapshot testing because the snapshot of components using `remock.renderProp` will change even though there is no change in the actual component.

Let me know if I'm being unclear and you need an example :)

**Comment by theKashey** [comment]
- `defaultMock` replaces a component with a "terminal" one (MockedOut).
- `renderProp` replaces using "transport" one (Transparent)

I left `itWas` only for debugging purposes, and it should be a string in both cases. It `renderProp` should not leave "type" behind, but shall use `getNameOf` as defaultMock does.

**Comment by theKashey** [comment]
Published as 0.7.1 (even if this is a (test) breaking change).

**Comment by bailer** [comment]
Awesome, thanks! I had prepared a PR but I wasn't sure that you agreed to the change so I appreciate the fast fix :)

**Comment by ms88privat** [comment]
Just wanted to thank you for this library 👍
